package main

type Dork struct {
	Baslik   string `json:"baslik"`
	Kategori string `json:"kategori"`
	Sorgu    string `json:"sorgu"`
	Link     string `json:"link"`
}

type Sablon struct {
	Baslik     string
	Kategori   string
	SorguMetni string
}

var SorguListesi = []Sablon{

	{Baslik: "Dizin Listeleme",
		Kategori:   "Hassas Dizinler",
		SorguMetni: "intitle:\"index of\" site:%s",
	},
	{Baslik: "Yedek Arşiv",
		Kategori:   "Yedekler",
		SorguMetni: "filetype:zip OR filetype:tar.gz \"backup\" site:%s",
	},
	{Baslik: "Apache Status",
		Kategori:   "Sistem",
		SorguMetni: "inurl:/server-status site:%s",
	},
	{Baslik: "API Anahtarları",
		Kategori:   "API",
		SorguMetni: "filetype:js \"api_key\" site:%s",
	},
	{Baslik: "Django Debug",
		Kategori:   "Hatalar",
		SorguMetni: "\"DisallowedHost at /\" site:%s",
	},
	{Baslik: "MongoDB Dökümü",
		Kategori:   "Veritabanı",
		SorguMetni: "filetype:json \"mongodb\" site:%s",
	},
	{Baslik: "Outlook Web Access",
		Kategori:   "Giriş Panelleri",
		SorguMetni: "inurl:/owa/ site:%s",
	},
	{Baslik: "Kullanıcı Verileri",
		Kategori:   "Şifreler",
		SorguMetni: "filetype:csv \"username\" \"password\" site:%s",
	},
	{Baslik: "FTP Dizinleri",
		Kategori:   "Dosya Paylaşımı",
		SorguMetni: "intitle:\"index of\" \"ftp\" site:%s",
	},
	{Baslik: "Sistem Log Dizini",
		Kategori:   "Hassas Dizinler",
		SorguMetni: "intitle:\"index of\" \"/var/log/\" site:%s",
	},
	{Baslik: "Docker Compose",
		Kategori:   "Sistem",
		SorguMetni: "filetype:yml \"docker-compose\" site:%s",
	},
	{Baslik: "phpinfo Sayfası",
		Kategori:   "Sistem",
		SorguMetni: "inurl:phpinfo.php site:%s",
	},
	{Baslik: "SVN Kalıntısı",
		Kategori:   "Versiyon Kontrol",
		SorguMetni: "inurl:/.svn/entries site:%s",
	},
	{Baslik: "PHP Fatal Error",
		Kategori:   "Hatalar",
		SorguMetni: "\"Fatal error:\" site:%s",
	},
	{Baslik: "phpMyAdmin",
		Kategori:   "Giriş Panelleri",
		SorguMetni: "inurl:phpmyadmin site:%s",
	},
	{Baslik: "Şifre Listeleri",
		Kategori:   "Şifreler",
		SorguMetni: "filetype:txt \"passwd\" OR \"password\" site:%s",
	},
	{Baslik: "phpinfo Sayfası",
		Kategori:   "Sistem",
		SorguMetni: "inurl:phpinfo.php site:%s",
	},
	{Baslik: "Shell Dosyası",
		Kategori:   "Güvenlik",
		SorguMetni: "filetype:php \"r57shell\" OR \"c99shell\" site:%s",
	},
	{Baslik: "Grafana İzleme",
		Kategori:   "Sistem",
		SorguMetni: "intitle:\"Grafana\" site:%s",
	},
	{Baslik: "Yedek Klasörleri",
		Kategori:   "Hassas Dizinler",
		SorguMetni: "intitle:\"index of\" \"backup\" site:%s",
	},
	{Baslik: "Kibana Panel",
		Kategori:   "Sistem",
		SorguMetni: "intitle:\"Kibana\" site:%s",
	},
	{Baslik: "Git İfşası",
		Kategori:   "Versiyon Kontrol",
		SorguMetni: "inurl:/.git/config site:%s",
	},
	{Baslik: "Gizli PDF",
		Kategori:   "Belgeler",
		SorguMetni: "filetype:pdf \"confidential\" site:%s",
	},
	{Baslik: "SQLite Veritabanı",
		Kategori:   "Veritabanı",
		SorguMetni: "filetype:db OR filetype:sqlite site:%s",
	},
	{Baslik: "Webmail Arayüzü",
		Kategori:   "Giriş Panelleri",
		SorguMetni: "inurl:/webmail/ site:%s",
	},
	{Baslik: "SSH Özel Anahtar",
		Kategori:   "Güvenlik",
		SorguMetni: "filetype:key \"BEGIN RSA PRIVATE KEY\" site:%s",
	},
	{Baslik: "Jenkins Panel",
		Kategori:   "Sistem",
		SorguMetni: "intitle:\"Dashboard [Jenkins]\" site:%s",
	},
	{Baslik: "Swagger API",
		Kategori:   "API",
		SorguMetni: "inurl:swagger-ui.html site:%s",
	},
	{Baslik: "Finansal Tablo",
		Kategori:   "Belgeler",
		SorguMetni: "filetype:xls \"salary\" OR \"maaş\" site:%s",
	},
	{Baslik: "cPanel Giriş",
		Kategori:   "Giriş Panelleri",
		SorguMetni: "inurl:cpanel site:%s",
	},
	{Baslik: "Web Sunucu Config",
		Kategori:   "Yapılandırma",
		SorguMetni: "filetype:conf OR filetype:cfg site:%s",
	},
	{Baslik: "Ağ Yazıcısı",
		Kategori:   "IoT",
		SorguMetni: "intitle:\"HP LaserJet\" site:%s",
	},
	{Baslik: "E-Posta Arşivleri",
		Kategori:   "Hassas Dizinler",
		SorguMetni: "intitle:\"index of\" \"mail\" site:%s",
	},
	{Baslik: "SQL Hatası",
		Kategori:   "Hatalar",
		SorguMetni: "\"sql syntax error\" site:%s",
	},
	{Baslik: "Çevresel Değişkenler",
		Kategori:   "Yapılandırma",
		SorguMetni: "filetype:env \"DB_PASSWORD\" site:%s",
	},
	{Baslik: "Admin Paneli",
		Kategori:   "Giriş Panelleri",
		SorguMetni: "inurl:admin/login site:%s",
	},
	{Baslik: "SQL Dump Dosyası",
		Kategori:   "Veritabanı",
		SorguMetni: "filetype:sql \"INSERT INTO\" site:%s",
	},
	{Baslik: "IP Kamera",
		Kategori:   "IoT",
		SorguMetni: "intitle:\"webcamXP 5\" site:%s",
	},
	{Baslik: "Toplu Başlık Taraması (Allintitle)",
		Kategori:   "İstihbarat",
		SorguMetni: "allintitle:admin dashboard panel site:%s",
	},
	{Baslik: "Toplu URL Analizi (Allinurl)",
		Kategori:   "Sistem",
		SorguMetni: "allinurl:auth login php site:%s",
	},
	{Baslik: "Toplu Metin Araması (Allintext)",
		Kategori:   "Sızıntı",
		SorguMetni: "allintext:\"kimlik no\" \"telefon\" site:%s",
	},
	{Baslik: "Google Önbellek Sorgusu (Cache)",
		Kategori:   "İstihbarat",
		SorguMetni: "cache:%s",
	},
	{Baslik: "Benzer Altyapı Analizi (Related)",
		Kategori:   "İstihbarat",
		SorguMetni: "related:%s",
	},
	{Baslik: "Site Teknik Bilgisi (Info)",
		Kategori:   "İstihbarat",
		SorguMetni: "info:%s",
	},
	{Baslik: "Uzantı Odaklı Arama (Ext)",
		Kategori:   "Belgeler",
		SorguMetni: "site:%s ext:log OR ext:env",
	},
	{Baslik: "Metin İçi Hassas Veri (Intext)",
		Kategori:   "Sızıntı",
		SorguMetni: "intext:\"gizli\" site:%s",
	},
	{Baslik: "Bağlantı Veren Siteler (Link)",
		Kategori:   "İstihbarat",
		SorguMetni: "link:%s",
	},
	{Baslik: "TC Sayı Dizisi (PDF)",
		Kategori:   "Kişisel Veri",
		SorguMetni: "site:%s filetype:pdf 10000000000..99999999998",
	},
	{Baslik: "Telefon No (Mobil 05xx)",
		Kategori:   "İletişim",
		SorguMetni: "site:%s 05000000000..05600000000",
	},
	{Baslik: "Öğrenci/Okul No Aralığı",
		Kategori:   "Eğitim",
		SorguMetni: "site:%s 201000000..202699999",
	},
	{Baslik: "Personel Mail Listesi",
		Kategori:   "İstihbarat",
		SorguMetni: "filetype:txt OR filetype:csv \"@%s\"",
	},
	{Baslik: "E-Posta Dökümleri",
		Kategori:   "Hassas Dizinler",
		SorguMetni: "site:%s intitle:\"index of\" mail",
	},
}
